name: build master code
on: [push]
jobs:
  build-code-actions:
    runs-on: ubuntu-latest
    steps:
      - run: apt update 
            && apt install build-essential -y
            && apt install cmake -y
            && apt install make -y
      - run: mkdir build && cd build && cmake .. && make
      - run: ./main
