name: build master code
on: [push]
jobs:
  build-code-actions:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update 
            && sudo apt install build-essential -y
            && sudo apt install cmake -y
            && sudo apt install make -y
      - run: pwd
      - run: mkdir -p build && cd build && cmake .. && make
      - run: ./main
